/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/recent`; params?: Router.UnknownInputParams; } | { pathname: `/search-location`; params?: Router.UnknownInputParams; } | { pathname: `/search-number`; params?: Router.UnknownInputParams; } | { pathname: `/../store/accessibilityStore`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AccessibilityPanel`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useA11y`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/station/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/recent`; params?: Router.UnknownOutputParams; } | { pathname: `/search-location`; params?: Router.UnknownOutputParams; } | { pathname: `/search-number`; params?: Router.UnknownOutputParams; } | { pathname: `/../store/accessibilityStore`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/AccessibilityPanel`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useA11y`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/station/[code]`, params: Router.UnknownOutputParams & { code: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/recent${`?${string}` | `#${string}` | ''}` | `/search-location${`?${string}` | `#${string}` | ''}` | `/search-number${`?${string}` | `#${string}` | ''}` | `/../store/accessibilityStore${`?${string}` | `#${string}` | ''}` | `/../components/AccessibilityPanel${`?${string}` | `#${string}` | ''}` | `/../hooks/useA11y${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorites${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/recent`; params?: Router.UnknownInputParams; } | { pathname: `/search-location`; params?: Router.UnknownInputParams; } | { pathname: `/search-number`; params?: Router.UnknownInputParams; } | { pathname: `/../store/accessibilityStore`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AccessibilityPanel`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useA11y`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/station/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/station/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
    }
  }
}
